// ============================================================
// MainActivity.kt — The Android side of our app.
//
// This is where we set up Platform Channels to expose Android
// and Linux kernel APIs to Flutter that aren't available
// through any Flutter package.
//
// A MethodChannel is a named communication pipe between
// Flutter (Dart) and Android (Kotlin). Flutter calls a method
// by name, Kotlin handles it and returns a result.
//
// Docs: https://docs.flutter.dev/platform-integration/platform-channels
// ============================================================
package com.ni6hant.systeminfo

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import java.io.File
import java.io.RandomAccessFile

class MainActivity : FlutterActivity() {

    // The channel name must match exactly what Flutter uses
    // Convention is reverse domain + descriptive name
    private val CPU_CHANNEL = "com.ni6hant.systeminfo/cpu"

    // ============================================================
    // configureFlutterEngine() — Called when Flutter engine starts.
    // This is where we register our Platform Channels.
    // Docs: https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html
    // ============================================================
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        // Create a MethodChannel with our chosen name
        // Flutter will use this exact name to communicate
        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CPU_CHANNEL
        ).setMethodCallHandler { call, result ->

            // 'call.method' is the method name Flutter sent
            // We handle each method name with a when block
            // (when is Kotlin's version of switch/match)
            when (call.method) {
                "getCpuInfo" -> {
                    try {
                        // Call our CPU info gathering function
                        // and return the result map to Flutter
                        result.success(getCpuInfo())
                    } catch (e: Exception) {
                        // If anything fails send the error back
                        // to Flutter so it can handle it gracefully
                        result.error(
                            "CPU_ERROR",
                            e.message,
                            null
                        )
                    }
                }

                // If Flutter calls a method we don't recognize
                // we must call notImplemented() — this is required
                // by the Platform Channel protocol
                else -> result.notImplemented()
            }
        }
    }

    // ============================================================
    // getCpuInfo() — Reads CPU information from the Linux kernel.
    //
    // Android is built on Linux so we can read from the /proc and
    // /sys virtual filesystems which expose kernel information.
    // These aren't real files on disk — they're generated by the
    // kernel on demand when read.
    //
    // /proc/cpuinfo — CPU hardware details
    // /sys/devices/system/cpu/ — CPU frequency and core info
    // ============================================================
    private fun getCpuInfo(): Map<String, String> {
        val info = mutableMapOf<String, String>()

        // ── Core Count ─────────────────────────────────────────
        // Runtime.availableProcessors() returns the number of
        // CPU cores currently available to the Android runtime.
        // This may be less than total cores if some are offline
        // to save power (a common technique called CPU hotplugging)
        // Docs: https://developer.android.com/reference/java/lang/Runtime
        info["availableCores"] = Runtime.getRuntime()
            .availableProcessors()
            .toString()

        // ── Total Core Count ───────────────────────────────────
        // /sys/devices/system/cpu/possible tells us the total
        // number of CPU cores including offline ones.
        // Format is "0-7" for 8 cores, "0-3" for 4 cores etc.
        try {
            val possible = File("/sys/devices/system/cpu/possible")
                .readText()
                .trim()
            // Parse "0-7" format to get total count
            // split("-") gives us ["0", "7"]
            // last() gives us "7", toInt() + 1 gives us 8
            val parts = possible.split("-")
            if (parts.size == 2) {
                val totalCores = parts.last().toInt() + 1
                info["totalCores"] = totalCores.toString()
            } else {
                info["totalCores"] = info["availableCores"] ?: "Unknown"
            }
        } catch (e: Exception) {
            info["totalCores"] = info["availableCores"] ?: "Unknown"
        }

        // ── CPU Governor ───────────────────────────────────────
        // The CPU governor controls how the CPU scales its speed.
        // Common governors: performance, powersave, schedutil,
        // interactive, ondemand
        // schedutil is most common on modern Android devices
        try {
            info["governor"] = File(
                "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
            ).readText().trim()
        } catch (e: Exception) {
            info["governor"] = "Unavailable"
        }

        // ── Maximum CPU Frequency ──────────────────────────────
        // The maximum clock speed this CPU can run at in kHz.
        // We convert to MHz and GHz for readability.
        // Docs: kernel.org/doc/html/latest/admin-guide/pm/cpufreq.html
        try {
            val maxFreqKHz = File(
                "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq"
            ).readText().trim().toLong()

            val maxFreqMHz = maxFreqKHz / 1000
            val maxFreqGHz = maxFreqMHz / 1000.0

            info["maxFrequency"] = "${maxFreqGHz.toBigDecimal()
                .setScale(2, java.math.RoundingMode.HALF_UP)}GHz " +
                    "(${maxFreqMHz}MHz)"
        } catch (e: Exception) {
            info["maxFrequency"] = "Unavailable"
        }

        // ── Minimum CPU Frequency ──────────────────────────────
        // The minimum clock speed — what the CPU runs at when idle
        try {
            val minFreqKHz = File(
                "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq"
            ).readText().trim().toLong()

            val minFreqMHz = minFreqKHz / 1000
            info["minFrequency"] = "${minFreqMHz}MHz"
        } catch (e: Exception) {
            info["minFrequency"] = "Unavailable"
        }

        // ── CPU Hardware Name ──────────────────────────────────
        // /proc/cpuinfo contains the hardware name reported by
        // the kernel. We look for the "Hardware" line.
        // This is partially readable on modern Android.
        try {
            val cpuInfo = File("/proc/cpuinfo").readText()
            val hardwareLine = cpuInfo.lines()
                .firstOrNull { it.startsWith("Hardware") }
            if (hardwareLine != null) {
                info["hardware"] = hardwareLine
                    .substringAfter(":").trim()
            } else {
                info["hardware"] = "Unavailable"
            }
        } catch (e: Exception) {
            info["hardware"] = "Unavailable"
        }

        // ── CPU Features ───────────────────────────────────────
        // Features line from /proc/cpuinfo lists supported
        // instruction set extensions like NEON, VFP, AES etc.
        try {
            val cpuInfo = File("/proc/cpuinfo").readText()
            val featuresLine = cpuInfo.lines()
                .firstOrNull { 
                    it.startsWith("Features") || 
                    it.startsWith("flags") 
                }
            if (featuresLine != null) {
                info["features"] = featuresLine
                    .substringAfter(":").trim()
            } else {
                info["features"] = "Unavailable"
            }
        } catch (e: Exception) {
            info["features"] = "Unavailable"
        }

        return info
    }
}